// <auto-generated />
using System;
using DrinkManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrinkManagement.Migrations
{
    [DbContext(typeof(DrinkDbContext))]
    partial class DrinkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DrinkManagement.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4046),
                            Description = "各类茶饮料",
                            Name = "茶饮"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4049),
                            Description = "咖啡类饮品",
                            Name = "咖啡"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4051),
                            Description = "鲜榨果汁",
                            Name = "果汁"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4052),
                            Description = "奶茶系列",
                            Name = "奶茶"
                        });
                });

            modelBuilder.Entity("DrinkManagement.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4183),
                            Description = "清新绿茶",
                            Name = "绿茶",
                            Price = 8.00m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4183)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4189),
                            Description = "经典红茶",
                            Name = "红茶",
                            Price = 8.00m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4189)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4191),
                            Description = "浓郁美式",
                            Name = "美式咖啡",
                            Price = 15.00m,
                            Stock = 80,
                            UpdatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4191)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4193),
                            Description = "香醇拿铁",
                            Name = "拿铁",
                            Price = 18.00m,
                            Stock = 80,
                            UpdatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4193)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4194),
                            Description = "鲜榨橙汁",
                            Name = "橙汁",
                            Price = 12.00m,
                            Stock = 60,
                            UpdatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4195)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4196),
                            Description = "经典珍珠奶茶",
                            Name = "珍珠奶茶",
                            Price = 10.00m,
                            Stock = 90,
                            UpdatedAt = new DateTime(2025, 12, 23, 3, 40, 53, 375, DateTimeKind.Utc).AddTicks(4196)
                        });
                });

            modelBuilder.Entity("DrinkManagement.Models.Drink", b =>
                {
                    b.HasOne("DrinkManagement.Models.Category", "Category")
                        .WithMany("Drinks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DrinkManagement.Models.Category", b =>
                {
                    b.Navigation("Drinks");
                });
#pragma warning restore 612, 618
        }
    }
}
